name: StationXec
version: 0.2.4
api-version: 1.12.2
author: Sinapole_Dora
main: org.minecraft.bukkit.com.syapole.stationxec.Main

commands:
  card:
    description: "Get a transportation card."
    usage: /<command>
    aliases: [iccard, tcard]
    permission: stationxec.getcard
    permission-message: "You don't have permission to perform this command."
  refound:
    description: "Regain the card you lost."
    usage: /<command>
    permission: stationxec.refound
    permission-message: "You don't have permission to perform this command."