name: StationXec
version: 0.2.5
api-version: 1.12.2
author: Sinapole_Dora
main: org.minecraft.bukkit.com.syapole.stationxec.Main

commands:
  controller:
    description: "Get the controller of the Platform screen door."
    usage: /<command>
    aliases: [cont]
    permission: stationxec.getitem
    permission-message: "You need permission to performance this command"